# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Benoit Clair
tagline:          'Personal page'
description:      'Portfolio management & computer scientist @<a href="http://edf.com" target="_blank">EDF Lab</a>.'
url:              https://bclair.eu
baseurl:          https://bclair.eu/

author:
  name:           'Benoit Clair'
  url:            https://twitter.com/benoit_clair

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/paronax/

linkedin:         https://www.linkedin.com/in/bclair/?locale=en_US
twitter:          https://twitter.com/benoit_clair
